server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: patient-history-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hospital_platform}
    username: ${SPRING_DATASOURCE_USERNAME:hospital}
    password: ${SPRING_DATASOURCE_PASSWORD:hospital}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: schema_history
  flyway:
    enabled: true
    default-schema: schema_history
    schemas: schema_history
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:hospital}
    password: ${SPRING_RABBITMQ_PASSWORD:hospital}
  graphql:
    graphiql:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

jwt:
  secret: ${APP_SECURITY_JWT_SECRET:change-me-in-local-please-use-a-very-long-secret-key-1234567890}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSS} %-5level [%X{correlationId}] %logger{36} - %msg%n"
